import { ExecutionMilestoneMonth, ExecutionScorecardItem } from './types';

export const SLIDE_09_COPY = {
  headerTitle: {
    id: 'Rencana Eksekusi 90 Hari',
    en: '90-Day Execution Plan',
  },
  headerBadge: {
    id: 'TOTAL 90 HARI (Q4: OKT–DES): RP 3,0 MILIAR',
    en: 'INITIAL 90-DAY TOTAL (Q4: OCT–DEC): IDR 3.0B',
  },
  quoteFooter: {
    id: '"Eksekusi dimulai Oktober (Q4): Bulan 1 (Oktober) membangun fondasi & PoC (Rp 0), Bulan 2 (November) achieve perdana Rp 1,0 Miliar, dan Bulan 3 (Desember) akselerasi growth Rp 2,0 Miliar — menutup Kuartal 4 (Q4) dengan sempurna mengunci total Rp 3,0 Miliar (3 Deals Won)."',
    en: '"Execution launches October (Full Q4): Month 1 (October) establishes foundation & PoC (IDR 0), Month 2 (November) achieves first win IDR 1.0B, and Month 3 (December) accelerates growth to IDR 2.0B — closing Quarter 4 flawlessly locking IDR 3.0B total (3 Deals Won)."',
  },
} as const;

export const EXECUTION_MILESTONE_MONTHS: ExecutionMilestoneMonth[] = [
  {
    id: 'month_1',
    monthNumber: 1,
    tagId: 'BULAN 1 (OKT) · HARI 1–30',
    tagEn: 'MONTH 1 (OCT) · DAYS 1–30',
    subtitle: 'PENGUMPULAN DATA & POC',
    targetRevenueLabelId: 'Target Revenue Bulan 1',
    targetRevenueLabelEn: 'Target Revenue Month 1',
    targetRevenueValue: 'Rp 0 (Pengumpulan Data & PoC)',
    revenueSubtext: 'Progres pengumpulan data 50 akun Jabodetabek, mining 300+ klien warm ITSEC, & 6 PoC 5-hari',
    focusKeyActionTitle: 'FOKUS AKSI KUNCI:',
    focusKeyActionDesc: 'Pemetaan 50 akun Jabodetabek, penambangan 300+ klien warm ITSEC Asia, dan peluncuran 6 PoC 5-hari staging tanpa risiko disrupsi.',
    bullets: [
      { text: '50 Akun Terpetakan & Dinilai' },
      { text: '6 PoC 5-Hari Staging Berjalan' },
      { text: 'Pipeline Buffer Rp 9,0 Miliar Terkunci' },
    ],
    footerStatus: 'Status: Fondasi & Pipeline Siap',
    footerBadge: '100% On-Track',
    theme: {
      containerBorder: 'border border-neutral-800',
      tagBg: 'bg-rose-950',
      tagText: 'text-rose-300',
      tagBorder: 'border-rose-800',
      subtextColor: 'text-neutral-400 text-[10px]',
      counterColor: 'text-rose-400',
      subtextDetailColor: 'text-[10px] text-neutral-400 font-mono',
      focusTitleColor: 'text-rose-400',
      checkIconColor: 'text-rose-400',
      footerStatusColor: 'text-rose-400 font-semibold',
      footerBadgeColor: 'text-white',
    },
  },
  {
    id: 'month_2',
    monthNumber: 2,
    tagId: 'BULAN 2 (NOV) · HARI 31–60',
    tagEn: 'MONTH 2 (NOV) · DAYS 31–60',
    subtitle: 'FIRST WIN CLOSING',
    targetRevenueLabelId: 'Target Revenue Bulan 2',
    targetRevenueLabelEn: 'Target Revenue Month 2',
    targetRevenueValue: 'Rp 1,0 Miliar',
    revenueSubtext: '1 Deal @ Rp 1M · Kuartal 4 (November) Sukses',
    focusKeyActionTitle: 'FOKUS AKSI KUNCI:',
    focusKeyActionDesc: 'Presentasi temuan celah kebocoran data C-Level, percepatan pengadaan via vendor code aktif, dan closing deal enterprise perdana.',
    bullets: [
      { text: '1 Kontrak Won Closing (Rp 1,0M ARR)', isBoldWhite: true },
      { text: '500 Device Terlindungi Penuh' },
      { text: 'Pipeline Tumbuh Menjadi Rp 15,0 Miliar' },
    ],
    footerStatus: 'Status: Achieve Perdana Tercapai',
    footerBadge: 'Q4 Attained',
    theme: {
      containerBorder: 'border border-neutral-800',
      tagBg: 'bg-amber-950',
      tagText: 'text-amber-300',
      tagBorder: 'border-amber-800',
      subtextColor: 'text-amber-400 text-[10px] font-bold',
      counterColor: 'text-amber-400',
      subtextDetailColor: 'text-[10px] text-amber-300 font-mono',
      focusTitleColor: 'text-amber-400',
      checkIconColor: 'text-amber-400',
      footerStatusColor: 'text-amber-400 font-semibold',
      footerBadgeColor: 'text-white',
    },
  },
  {
    id: 'month_3',
    monthNumber: 3,
    tagId: 'BULAN 3 (DES) · HARI 61–90',
    tagEn: 'MONTH 3 (DEC) · DAYS 61–90',
    subtitle: 'GROWTH ACCELERATION',
    targetRevenueLabelId: 'Target Revenue Bulan 3',
    targetRevenueLabelEn: 'Target Revenue Month 3',
    targetRevenueValue: 'Rp 2,0 Miliar',
    revenueSubtext: '2 Deals @ Rp 1M · Kumulatif 90 Hari (Q4 Penuh): Rp 3,0 Miliar (3 Deals)',
    focusKeyActionTitle: 'FOKUS AKSI KUNCI:',
    focusKeyActionDesc: 'Tutup 2 deal enterprise baru di Desember memanfaatkan Year-End Budget Flush, akselerasi growth Rp 2,0 M/bulan, aktifkan co-sell bersama Multipolar, Reycom Data Solusi & Mastersystem, dan kunci total Q4 Rp 3,0 Miliar.',
    bullets: [
      { text: '2 Kontrak Baru Won Closing (Rp 2,0M ARR)', isBoldWhite: true },
      { text: 'Total 90 Hari (Q4: Okt–Des) Rp 3,0 Miliar Terkunci (3 Deals)' },
      { text: 'Rolling Pipeline Buffer Rp 20,0 Miliar' },
    ],
    footerStatus: 'Hasil: Kuota Q4 (90 Hari) Tercapai Sempurna',
    footerBadge: 'HARRY GULTOM PROVEN',
    theme: {
      containerBorder: 'border-2 border-emerald-500',
      tagBg: 'bg-emerald-950',
      tagText: 'text-emerald-300',
      tagBorder: 'border-emerald-700',
      subtextColor: 'text-emerald-400 text-[10px] font-bold',
      counterColor: 'text-emerald-400',
      subtextDetailColor: 'text-[10px] text-emerald-300 font-mono font-bold',
      focusTitleColor: 'text-emerald-400',
      checkIconColor: 'text-emerald-400',
      footerStatusColor: 'text-emerald-300 font-bold',
      footerBadgeColor: 'text-emerald-400 font-mono',
    },
  },
];

export const EXECUTION_SCORECARD_ITEMS: ExecutionScorecardItem[] = [
  {
    id: 'metric_revenue',
    labelId: 'Total Revenue 90 Hari (Q4)',
    labelEn: '90-Day Revenue (Q4)',
    value: 'Rp 3,0 Miliar',
    badge: '3 Deals Won',
    badgeStyle: 'bg-emerald-950 text-emerald-300 border border-emerald-800 font-bold',
    valueColor: 'text-emerald-400',
  },
  {
    id: 'metric_accounts',
    labelId: 'Total Akun Aktif 90D',
    labelEn: 'Total Akun Aktif 90D',
    value: '3 Klien (1.500 Node)',
    badge: '500 Dev/Akun',
    badgeStyle: 'bg-neutral-900 text-neutral-300 border border-neutral-800',
    valueColor: 'text-white',
  },
  {
    id: 'metric_winrate',
    labelId: 'Win Rate PoC 5-Hari',
    labelEn: 'Win Rate PoC 5-Hari',
    value: '60% – 65%',
    badge: 'Empirical Proof',
    badgeStyle: 'bg-rose-950 text-rose-300 border border-rose-800 font-bold',
    valueColor: 'text-rose-400',
  },
  {
    id: 'metric_nrr',
    labelId: 'Net Revenue Retention',
    labelEn: 'Net Revenue Retention',
    value: '120% – 130%',
    badge: 'Land & Expand',
    badgeStyle: 'bg-sky-950 text-sky-300 border border-sky-800 font-bold',
    valueColor: 'text-sky-400',
  },
];
